baseurl = "https://nshine.dev"
title = "nshine.dev"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

googleAnalytics = "G-FEXQ1JENTB"

disableKinds = ["taxonomy", "term"]

[params]
    author = "Nicholas Shine"
    description = "Nick Shine's portfolio"
    keywords = "developer,portfolio,resume"
    info = "Full Stack Engineer"
    # avatarurl = "images/avatar.jpg"
    gravatar = "shine.nick@gmail.com"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideFooter = true
    hideCredits = true
    hideCopyright = true
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = true

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = ["css/extra.css"]

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# [taxonomies]
#   category = "categories"
#   series = "series"
#   tag = "tags"
#   author = "authors"

[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/nshine/"
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 2
    url = "https://github.com/nickshine/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fa fa-gitlab"
#     weight = 3
#     url = "https://gitlab.com/nickshine"
[[params.social]]
    name = "Acclaim"
    icon = "fa fa-certificate"
    weight = 4
    url = "https://www.youracclaim.com/users/nicholas-shine?Subject="
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 5
    url = "mailto:shine.nick@gmail.com?Subject=Hi from nshine.dev"
# [[params.social]]
#     name = "Twitter"
#     icon = "fa fa-twitter"
#     weight = 3
#     url = "https://twitter.com/nickshine/"
# [[params.social]]
#     name = "Medium"
#     icon = "fa fa-medium"
#     weight = 4
#     url = "https://medium.com/@nickshine"
# [[params.social]]
#     name = "RSS"
#     icon = "fa fa-rss"
#     weight = 6
#     url = "https://myhugosite.com/index.xml"
#     rel = "alternate"
#     type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            # [[languages.en.menu.main]]
            # name = "About"
            # weight = 1
            # url = "about/"

            # [[languages.en.menu.main]]
            # name = "Blog"
            # weight = 2
            # url = "posts/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3
            # url = "projects/"
